export const Types = {
  // send otp to phone
  SEND_MOBILE_OTP_REQUEST: "SEND_MOBILE_OTP_REQUEST",
  CREATE_NEW_USER: "CREATE_NEW_USER",
  CREATE_NEW_USER_SUCCESS: "CREATE_NEW_USER_SUCCESS",
  CREATE_NEW_USER_FAILURE: "CREATE_NEW_USER_FAILURE",
  SEND_MOBILE_OTP_SUCCESS: "SEND_MOBILE_OTP_SUCCESS",
  SEND_MOBILE_OTP_FAILURE: "SEND_MOBILE_OTP_FAILURE",

  //api call
  API_CALL_REQUEST: "API_CALL_REQUEST",
  API_CALL_SUCCESS: "API_CALL_SUCCESS",
  API_CALL_FAILURE: "API_CALL_FAILURE",

  // verify otp
  VERIFY_OTP_REQUEST: "VERIFY_OTP_REQUEST",
  VERIFY_OTP_SUCCESS: "VERIFY_OTP_SUCCESS",
  VERIFY_OTP_FAILURE: "VERIFY_OTP_FAILURE",

  // add address
  ADD_ADDRESS_REQUEST: "ADD_ADDRESS_REQUEST",
  ADD_ADDRESS_SUCCESS: "ADD_ADDRESS_SUCCESS",
  ADD_ADDRESS_FAILURE: "ADD_ADDRESS_FAILURE",

  // add user details
  ADD_DETAILS_REQUEST: "ADD_DETAILS_REQUEST",
  ADD_DETAILS_SUCCESS: "ADD_DETAILS_SUCCESS",
  ADD_DETAILS_FAILURE: "ADD_DETAILS_FAILURE",

  //land lord properties
  PROPERTIES_REQUEST: "PROPERTIES_REQUEST",
  PROPERTIES_SUCCESS: "PROPERTIES_SUCCESS",
  PROPERTIES_FAILURE: "PROPERTIES_FAILURE",

  // send otp to email
  SEND_EMAIL_OTP_REQUEST: "SEND_EMAIL_OTP_REQUEST",
  SEND_EMAIL_OTP_SUCCESS: "SEND_EMAIL_OTP_SUCCESS",
  SEND_EMAIL_OTP_FAILURE: "SEND_EMAIL_OTP_FAILURE",

  RESET_STATE:"RESET_STATE",
  RESET_ADDRESS:"RESET_ADDRESS",
  RESET_OTP:"RESET_OTP",

  UPDATE_STATE_VARIABLE: "UPDATE_STATE_VARIABLE",
  ON_COMPLETE_APPLICATION: "ON_COMPLETE_APPLICATION",

  ADD_PROPERTY_REQUEST: "ADD_PROPERTY_REQUEST",
  ADD_PROPERTY_SUCCESS: "ADD_PROPERTY_SUCCESS",
  ADD_PROPERTY_FAILURE: "ADD_PROPERTY_FAILURE",

  UPDATE_THEME: "UPDATE_THEME",

  // questions - application process
  APPLICATION_START: "APPLICATION_START",
  UPDATE_QUESTION: "UPDATE_QUESTION",
  GIVE_ANSWER: "GIVE_ANSWER",
  SET_LOADING: "SET_LOADING",
  APPLICATION_SUCCESS: "APPLICATION_SUCCESS",
  APPLICATION_FAILURE: "APPLICATION_FAILURE",
  SUBMIT_CASE_NO: "SUBMIT_CASE_NO",
  SUBMIT_AWARD_LETTER: "SUBMIT_AWARD_LETTER",
  SUMBIT_TAX_RETURN: "SUMBIT_TAX_RETURN",
  SUMBIT_INCOME_DOCS: "SUMBIT_INCOME_DOCS",
  SUBMIT_REASON: "SUBMIT_REASON",
};
